# $FreeBSD$

PORTNAME=	tubes2oe
PORTVERSION=	2.2
CATEGORIES=	science
MASTER_SITES=	http://www.pozsarzs.hu/sources/

MAINTAINER=	info@pozsarzs.hu
COMMENT=	Electron tube catalog

GNU_CONFIGURE=	yes

.include <bsd.port.mk>

CONFIGURE_ARGS+=stagedir=$(STAGEDIR)/$(PREFIX)

