Group: Sciences/Other
License: GPL
Name: tubes2-trial
Packager: Pozsar Zsolt <pozsarzs@gmail.com>
Release: 1
Summary: Electrontube catalog.
Url: http://www.pozsarzs.hu/tubes/tubes.html
Vendor: Pozsar Zsolt
Version: 2.0.2

%description
This is an electrontube catalog.
Its database contents base type, pin-out and some parameters of components.
This is a trial version: you can try out it with 'trial' version for free, but
if you decide to keep and use it you must register.

%files
/usr/bin/tubes2trial
/usr/share/man/man7/tubes2trial.7
/usr/share/man/man5/cxedf.5
/usr/share/man/man5/xedf.5
/usr/share/man/hu/man7/tubes2trial.7
/usr/share/man/hu/man5/cxedf.5
/usr/share/man/hu/man5/xedf.5
/usr/share/applications/tubes2trial.desktop
/usr/share/doc/tubes2trial/COPYING
/usr/share/doc/tubes2trial/AUTHORS
/usr/share/doc/tubes2trial/ChangeLog
/usr/share/doc/tubes2trial/free_reg_form.odt
/usr/share/doc/tubes2trial/free_reg_form.txt
/usr/share/doc/tubes2trial/support_form.pdf
/usr/share/doc/tubes2trial/README
/usr/share/doc/tubes2trial/reg_form.odt
/usr/share/doc/tubes2trial/reg_form.pdf
/usr/share/doc/tubes2trial/hu/free_reg_form.odt
/usr/share/doc/tubes2trial/hu/free_reg_form.txt
/usr/share/doc/tubes2trial/hu/support_form.pdf
/usr/share/doc/tubes2trial/hu/README
/usr/share/doc/tubes2trial/hu/reg_form.odt
/usr/share/doc/tubes2trial/hu/reg_form.pdf
/usr/share/doc/tubes2trial/hu/reg_form.txt
/usr/share/doc/tubes2trial/hu/INSTALL
/usr/share/doc/tubes2trial/hu/free_reg_form.pdf
/usr/share/doc/tubes2trial/hu/support_form.txt
/usr/share/doc/tubes2trial/hu/support_form.odt
/usr/share/doc/tubes2trial/reg_form.txt
/usr/share/doc/tubes2trial/INSTALL
/usr/share/doc/tubes2trial/free_reg_form.pdf
/usr/share/doc/tubes2trial/support_form.txt
/usr/share/doc/tubes2trial/support_form.odt
/usr/share/doc/tubes2trial/VERSION
/usr/share/locale/hu/LC_MESSAGES/tubes2trial.mo
/usr/share/pixmaps/tubes2trial.xpm
/usr/share/tubes2trial/library_hu/52.txt
/usr/share/tubes2trial/library_hu/60.xedf
/usr/share/tubes2trial/library_hu/37.xedf
/usr/share/tubes2trial/library_hu/39.txt
/usr/share/tubes2trial/library_hu/40.txt
/usr/share/tubes2trial/library_hu/34.xedf
/usr/share/tubes2trial/library_hu/15.xedf
/usr/share/tubes2trial/library_hu/51.xedf
/usr/share/tubes2trial/library_hu/19.txt
/usr/share/tubes2trial/library_hu/04.txt
/usr/share/tubes2trial/library_hu/41.txt
/usr/share/tubes2trial/library_hu/20.txt
/usr/share/tubes2trial/library_hu/57.txt
/usr/share/tubes2trial/library_hu/29.xedf
/usr/share/tubes2trial/library_hu/59.xedf
/usr/share/tubes2trial/library_hu/22.xedf
/usr/share/tubes2trial/library_hu/36.xedf
/usr/share/tubes2trial/library_hu/57.xedf
/usr/share/tubes2trial/library_hu/40.xedf
/usr/share/tubes2trial/library_hu/13.xedf
/usr/share/tubes2trial/library_hu/50.txt
/usr/share/tubes2trial/library_hu/05.xedf
/usr/share/tubes2trial/library_hu/28.txt
/usr/share/tubes2trial/library_hu/04.xedf
/usr/share/tubes2trial/library_hu/32.xedf
/usr/share/tubes2trial/library_hu/49.xedf
/usr/share/tubes2trial/library_hu/21.txt
/usr/share/tubes2trial/library_hu/31.xedf
/usr/share/tubes2trial/library_hu/15.txt
/usr/share/tubes2trial/library_hu/24.txt
/usr/share/tubes2trial/library_hu/56.txt
/usr/share/tubes2trial/library_hu/24.xedf
/usr/share/tubes2trial/library_hu/44.txt
/usr/share/tubes2trial/library_hu/18.txt
/usr/share/tubes2trial/library_hu/38.txt
/usr/share/tubes2trial/library_hu/60.txt
/usr/share/tubes2trial/library_hu/55.txt
/usr/share/tubes2trial/library_hu/26.xedf
/usr/share/tubes2trial/library_hu/41.xedf
/usr/share/tubes2trial/library_hu/47.xedf
/usr/share/tubes2trial/library_hu/03.xedf
/usr/share/tubes2trial/library_hu/42.txt
/usr/share/tubes2trial/library_hu/35.txt
/usr/share/tubes2trial/library_hu/version.txt
/usr/share/tubes2trial/library_hu/43.xedf
/usr/share/tubes2trial/library_hu/03.txt
/usr/share/tubes2trial/library_hu/58.txt
/usr/share/tubes2trial/library_hu/30.xedf
/usr/share/tubes2trial/library_hu/23.xedf
/usr/share/tubes2trial/library_hu/21.xedf
/usr/share/tubes2trial/library_hu/61.txt
/usr/share/tubes2trial/library_hu/news.txt
/usr/share/tubes2trial/library_hu/54.xedf
/usr/share/tubes2trial/library_hu/06.txt
/usr/share/tubes2trial/library_hu/38.xedf
/usr/share/tubes2trial/library_hu/42.xedf
/usr/share/tubes2trial/library_hu/27.xedf
/usr/share/tubes2trial/library_hu/53.txt
/usr/share/tubes2trial/library_hu/63.xedf
/usr/share/tubes2trial/library_hu/53.xedf
/usr/share/tubes2trial/library_hu/20.xedf
/usr/share/tubes2trial/library_hu/54.txt
/usr/share/tubes2trial/library_hu/49.txt
/usr/share/tubes2trial/library_hu/45.xedf
/usr/share/tubes2trial/library_hu/32.txt
/usr/share/tubes2trial/library_hu/43.txt
/usr/share/tubes2trial/library_hu/34.txt
/usr/share/tubes2trial/library_hu/17.txt
/usr/share/tubes2trial/library_hu/62.xedf
/usr/share/tubes2trial/library_hu/07.txt
/usr/share/tubes2trial/library_hu/62.txt
/usr/share/tubes2trial/library_hu/19.xedf
/usr/share/tubes2trial/library_hu/05.txt
/usr/share/tubes2trial/library_hu/36.txt
/usr/share/tubes2trial/library_hu/61.xedf
/usr/share/tubes2trial/library_hu/23.txt
/usr/share/tubes2trial/library_hu/27.txt
/usr/share/tubes2trial/library_hu/58.xedf
/usr/share/tubes2trial/library_hu/59.txt
/usr/share/tubes2trial/library_hu/18.xedf
/usr/share/tubes2trial/library_hu/48.xedf
/usr/share/tubes2trial/library_hu/33.xedf
/usr/share/tubes2trial/library_hu/55.xedf
/usr/share/tubes2trial/library_hu/47.txt
/usr/share/tubes2trial/library_hu/46.xedf
/usr/share/tubes2trial/library_hu/50.xedf
/usr/share/tubes2trial/library_hu/29.txt
/usr/share/tubes2trial/library_hu/02.xedf
/usr/share/tubes2trial/library_hu/45.txt
/usr/share/tubes2trial/library_hu/07.xedf
/usr/share/tubes2trial/library_hu/26.txt
/usr/share/tubes2trial/library_hu/52.xedf
/usr/share/tubes2trial/library_hu/33.txt
/usr/share/tubes2trial/library_hu/01.xedf
/usr/share/tubes2trial/library_hu/30.txt
/usr/share/tubes2trial/library_hu/31.txt
/usr/share/tubes2trial/library_hu/48.txt
/usr/share/tubes2trial/library_hu/06.xedf
/usr/share/tubes2trial/library_hu/51.txt
/usr/share/tubes2trial/library_hu/63.txt
/usr/share/tubes2trial/library_hu/35.xedf
/usr/share/tubes2trial/library_hu/37.txt
/usr/share/tubes2trial/library_hu/56.xedf
/usr/share/tubes2trial/library_hu/22.txt
/usr/share/tubes2trial/library_hu/01.txt
/usr/share/tubes2trial/library_hu/39.xedf
/usr/share/tubes2trial/library_hu/28.xedf
/usr/share/tubes2trial/library_hu/46.txt
/usr/share/tubes2trial/library_hu/13.txt
/usr/share/tubes2trial/library_hu/02.txt
/usr/share/tubes2trial/library_hu/44.xedf
/usr/share/tubes2trial/library_hu/17.xedf
/usr/share/tubes2trial/help_hu/dialog_tsearchallcat.html
/usr/share/tubes2trial/help_hu/main_file.html
/usr/share/tubes2trial/help_hu/support.html
/usr/share/tubes2trial/help_hu/local_pinout.html
/usr/share/tubes2trial/help_hu/registration.html
/usr/share/tubes2trial/help_hu/sign_euro.html
/usr/share/tubes2trial/help_hu/sign_philips.html
/usr/share/tubes2trial/help_hu/local_table.html
/usr/share/tubes2trial/help_hu/sign_cv.html
/usr/share/tubes2trial/help_hu/sign_soviet.html
/usr/share/tubes2trial/help_hu/dialog_sort.html
/usr/share/tubes2trial/help_hu/introduction.html
/usr/share/tubes2trial/help_hu/pics/dialog_set.jpg
/usr/share/tubes2trial/help_hu/pics/local1.jpg
/usr/share/tubes2trial/help_hu/pics/dialog_psearch.jpg
/usr/share/tubes2trial/help_hu/pics/main3.jpg
/usr/share/tubes2trial/help_hu/pics/dialog_tsearchallcat.jpg
/usr/share/tubes2trial/help_hu/pics/local4.jpg
/usr/share/tubes2trial/help_hu/pics/local2.jpg
/usr/share/tubes2trial/help_hu/pics/main2.jpg
/usr/share/tubes2trial/help_hu/pics/local3.jpg
/usr/share/tubes2trial/help_hu/pics/dialog_sort.jpg
/usr/share/tubes2trial/help_hu/pics/main1.jpg
/usr/share/tubes2trial/help_hu/pics/main5.jpg
/usr/share/tubes2trial/help_hu/pics/main4.jpg
/usr/share/tubes2trial/help_hu/pics/dialog_tsearch.jpg
/usr/share/tubes2trial/help_hu/dialog_tsearch.html
/usr/share/tubes2trial/help_hu/sign_mazda.html
/usr/share/tubes2trial/help_hu/dialog_settings.html
/usr/share/tubes2trial/help_hu/main_search.html
/usr/share/tubes2trial/help_hu/sign_usa.html
/usr/share/tubes2trial/help_hu/cmdparams.html
/usr/share/tubes2trial/help_hu/sign_brimar.html
/usr/share/tubes2trial/help_hu/main_view.html
/usr/share/tubes2trial/help_hu/contact.html
/usr/share/tubes2trial/help_hu/local_bms.html
/usr/share/tubes2trial/help_hu/main_bms.html
/usr/share/tubes2trial/help_hu/index.html
/usr/share/tubes2trial/help_hu/main_help.html
/usr/share/tubes2trial/help_hu/hotkeys.html
/usr/share/tubes2trial/help_hu/free_registration.html
/usr/share/tubes2trial/help_hu/dialog_psearch.html
/usr/share/tubes2trial/help_hu/local_desc.html
/usr/share/tubes2trial/base/xb4.png
/usr/share/tubes2trial/base/sk-136.png
/usr/share/tubes2trial/base/spec1.png
/usr/share/tubes2trial/base/xs7.png
/usr/share/tubes2trial/base/u6.png
/usr/share/tubes2trial/base/xa10.png
/usr/share/tubes2trial/base/x8.png
/usr/share/tubes2trial/base/s5.png
/usr/share/tubes2trial/base/to-100.png
/usr/share/tubes2trial/base/eu5.png
/usr/share/tubes2trial/base/ed2.png
/usr/share/tubes2trial/base/wire-2.png
/usr/share/tubes2trial/base/b7.png
/usr/share/tubes2trial/base/b17a.png
/usr/share/tubes2trial/base/b8d.png
/usr/share/tubes2trial/base/u4.png
/usr/share/tubes2trial/base/k5a.png
/usr/share/tubes2trial/base/crt-12.png
/usr/share/tubes2trial/base/b6.png
/usr/share/tubes2trial/base/wire-4.png
/usr/share/tubes2trial/base/y11.png
/usr/share/tubes2trial/base/eu4.png
/usr/share/tubes2trial/base/b9aplus.png
/usr/share/tubes2trial/base/crt-14a.png
/usr/share/tubes2trial/base/ed1.png
/usr/share/tubes2trial/base/b9a.png
/usr/share/tubes2trial/base/sk-116.png
/usr/share/tubes2trial/base/p7.png
/usr/share/tubes2trial/base/xa3.png
/usr/share/tubes2trial/base/k8a.png
/usr/share/tubes2trial/base/eugrd.png
/usr/share/tubes2trial/base/u5.png
/usr/share/tubes2trial/base/es2.png
/usr/share/tubes2trial/base/y9.png
/usr/share/tubes2trial/base/xc4.png
/usr/share/tubes2trial/base/uo1.png
/usr/share/tubes2trial/base/xs9.png
/usr/share/tubes2trial/base/wire-4a.png
/usr/share/tubes2trial/base/wire-3a.png
/usr/share/tubes2trial/base/a8.png
/usr/share/tubes2trial/base/xa11.png
/usr/share/tubes2trial/base/wire-5a.png
/usr/share/tubes2trial/base/wire-3.png
/usr/share/tubes2trial/base/x8a.png
/usr/share/tubes2trial/base/crt-14b.png
/usr/share/tubes2trial/base/bb7.png
/usr/share/tubes2trial/base/dip-16.png
/usr/share/tubes2trial/base/u7.png
/usr/share/tubes2trial/base/sk-207.png
/usr/share/tubes2trial/base/wire-5.png
/usr/share/tubes2trial/base/xo6.png
/usr/share/tubes2trial/base/b13b.png
/usr/share/tubes2trial/base/ed3.png
/usr/share/tubes2trial/base/xo11.png
/usr/share/tubes2trial/base/b8g.png
/usr/share/tubes2trial/base/sk-185.png
/usr/share/tubes2trial/base/solder_tag_16.png
/usr/share/tubes2trial/base/wire-6a.png
/usr/share/tubes2trial/base/b7g.png
/usr/share/tubes2trial/base/k5.png
/usr/share/tubes2trial/base/y6.png
/usr/share/tubes2trial/base/crt-18.png
/usr/share/tubes2trial/base/es1.png
/usr/share/tubes2trial/base/x5.png
/usr/share/tubes2trial/base/rts-11.png
/usr/share/tubes2trial/base/ho1.png
/usr/share/tubes2trial/base/w8.png
/usr/share/tubes2trial/base/b13d.png
/usr/share/tubes2trial/base/x6.png
/usr/share/tubes2trial/base/b14a.png
/usr/share/tubes2trial/base/b9d.png
/usr/share/tubes2trial/base/p5.png
/usr/share/tubes2trial/base/r8.png
/usr/share/tubes2trial/base/w8a.png
/usr/share/tubes2trial/base/xo2.png
/usr/share/tubes2trial/base/wire-9.png
/usr/share/tubes2trial/base/sk-176.png
/usr/share/tubes2trial/base/a10.png
/usr/share/tubes2trial/base/x3.png
/usr/share/tubes2trial/base/t9.png
/usr/share/tubes2trial/base/xa5.png
/usr/share/tubes2trial/base/sk-197.png
/usr/share/tubes2trial/base/xe7.png
/usr/share/tubes2trial/base/sk-182.png
/usr/share/tubes2trial/base/crt-11.png
/usr/share/tubes2trial/base/y5.png
/usr/share/tubes2trial/base/x7.png
/usr/share/tubes2trial/base/mo3.png
/usr/share/tubes2trial/base/xs10.png
/usr/share/tubes2trial/base/k8alh.png
/usr/share/tubes2trial/base/k8.png
/usr/share/tubes2trial/base/eu3.png
/usr/share/tubes2trial/base/crt-14.png
/usr/share/tubes2trial/base/b12a.png
/usr/share/tubes2trial/base/wire-7a.png
/usr/share/tubes2trial/base/eo1.png
/usr/share/tubes2trial/base/b12e.png
/usr/share/tubes2trial/base/sk-118.png
/usr/share/tubes2trial/base/crt-14c.png
/usr/share/tubes2trial/base/crt-11a.png
/usr/share/tubes2trial/base/s8.png
/usr/share/tubes2trial/base/wire-2a.png
/usr/share/tubes2trial/base/f5.png
/usr/share/tubes2trial/base/unknown.png
/usr/share/tubes2trial/base/y3.png
/usr/share/tubes2trial/base/b5.png
/usr/share/tubes2trial/base/xa4.png
/usr/share/tubes2trial/library_en/52.txt
/usr/share/tubes2trial/library_en/60.xedf
/usr/share/tubes2trial/library_en/37.xedf
/usr/share/tubes2trial/library_en/39.txt
/usr/share/tubes2trial/library_en/40.txt
/usr/share/tubes2trial/library_en/34.xedf
/usr/share/tubes2trial/library_en/15.xedf
/usr/share/tubes2trial/library_en/51.xedf
/usr/share/tubes2trial/library_en/19.txt
/usr/share/tubes2trial/library_en/04.txt
/usr/share/tubes2trial/library_en/41.txt
/usr/share/tubes2trial/library_en/20.txt
/usr/share/tubes2trial/library_en/57.txt
/usr/share/tubes2trial/library_en/29.xedf
/usr/share/tubes2trial/library_en/59.xedf
/usr/share/tubes2trial/library_en/22.xedf
/usr/share/tubes2trial/library_en/36.xedf
/usr/share/tubes2trial/library_en/57.xedf
/usr/share/tubes2trial/library_en/13.xedf
/usr/share/tubes2trial/library_en/50.txt
/usr/share/tubes2trial/library_en/05.xedf
/usr/share/tubes2trial/library_en/28.txt
/usr/share/tubes2trial/library_en/04.xedf
/usr/share/tubes2trial/library_en/32.xedf
/usr/share/tubes2trial/library_en/49.xedf
/usr/share/tubes2trial/library_en/21.txt
/usr/share/tubes2trial/library_en/31.xedf
/usr/share/tubes2trial/library_en/15.txt
/usr/share/tubes2trial/library_en/24.txt
/usr/share/tubes2trial/library_en/56.txt
/usr/share/tubes2trial/library_en/24.xedf
/usr/share/tubes2trial/library_en/44.txt
/usr/share/tubes2trial/library_en/18.txt
/usr/share/tubes2trial/library_en/38.txt
/usr/share/tubes2trial/library_en/60.txt
/usr/share/tubes2trial/library_en/55.txt
/usr/share/tubes2trial/library_en/26.xedf
/usr/share/tubes2trial/library_en/41.xedf
/usr/share/tubes2trial/library_en/47.xedf
/usr/share/tubes2trial/library_en/03.xedf
/usr/share/tubes2trial/library_en/42.txt
/usr/share/tubes2trial/library_en/35.txt
/usr/share/tubes2trial/library_en/version.txt
/usr/share/tubes2trial/library_en/43.xedf
/usr/share/tubes2trial/library_en/03.txt
/usr/share/tubes2trial/library_en/58.txt
/usr/share/tubes2trial/library_en/30.xedf
/usr/share/tubes2trial/library_en/23.xedf
/usr/share/tubes2trial/library_en/21.xedf
/usr/share/tubes2trial/library_en/61.txt
/usr/share/tubes2trial/library_en/news.txt
/usr/share/tubes2trial/library_en/54.xedf
/usr/share/tubes2trial/library_en/06.txt
/usr/share/tubes2trial/library_en/38.xedf
/usr/share/tubes2trial/library_en/42.xedf
/usr/share/tubes2trial/library_en/27.xedf
/usr/share/tubes2trial/library_en/53.txt
/usr/share/tubes2trial/library_en/63.xedf
/usr/share/tubes2trial/library_en/53.xedf
/usr/share/tubes2trial/library_en/20.xedf
/usr/share/tubes2trial/library_en/54.txt
/usr/share/tubes2trial/library_en/49.txt
/usr/share/tubes2trial/library_en/45.xedf
/usr/share/tubes2trial/library_en/32.txt
/usr/share/tubes2trial/library_en/43.txt
/usr/share/tubes2trial/library_en/34.txt
/usr/share/tubes2trial/library_en/17.txt
/usr/share/tubes2trial/library_en/62.xedf
/usr/share/tubes2trial/library_en/07.txt
/usr/share/tubes2trial/library_en/62.txt
/usr/share/tubes2trial/library_en/19.xedf
/usr/share/tubes2trial/library_en/05.txt
/usr/share/tubes2trial/library_en/36.txt
/usr/share/tubes2trial/library_en/61.xedf
/usr/share/tubes2trial/library_en/23.txt
/usr/share/tubes2trial/library_en/27.txt
/usr/share/tubes2trial/library_en/58.xedf
/usr/share/tubes2trial/library_en/59.txt
/usr/share/tubes2trial/library_en/18.xedf
/usr/share/tubes2trial/library_en/48.xedf
/usr/share/tubes2trial/library_en/33.xedf
/usr/share/tubes2trial/library_en/55.xedf
/usr/share/tubes2trial/library_en/47.txt
/usr/share/tubes2trial/library_en/46.xedf
/usr/share/tubes2trial/library_en/50.xedf
/usr/share/tubes2trial/library_en/29.txt
/usr/share/tubes2trial/library_en/02.xedf
/usr/share/tubes2trial/library_en/45.txt
/usr/share/tubes2trial/library_en/07.xedf
/usr/share/tubes2trial/library_en/26.txt
/usr/share/tubes2trial/library_en/52.xedf
/usr/share/tubes2trial/library_en/33.txt
/usr/share/tubes2trial/library_en/01.xedf
/usr/share/tubes2trial/library_en/30.txt
/usr/share/tubes2trial/library_en/31.txt
/usr/share/tubes2trial/library_en/48.txt
/usr/share/tubes2trial/library_en/06.xedf
/usr/share/tubes2trial/library_en/51.txt
/usr/share/tubes2trial/library_en/63.txt
/usr/share/tubes2trial/library_en/35.xedf
/usr/share/tubes2trial/library_en/37.txt
/usr/share/tubes2trial/library_en/56.xedf
/usr/share/tubes2trial/library_en/22.txt
/usr/share/tubes2trial/library_en/01.txt
/usr/share/tubes2trial/library_en/39.xedf
/usr/share/tubes2trial/library_en/28.xedf
/usr/share/tubes2trial/library_en/46.txt
/usr/share/tubes2trial/library_en/13.txt
/usr/share/tubes2trial/library_en/02.txt
/usr/share/tubes2trial/library_en/44.xedf
/usr/share/tubes2trial/library_en/17.xedf
/usr/share/tubes2trial/index.csv
/usr/share/tubes2trial/help_en/dialog_tsearchallcat.html
/usr/share/tubes2trial/help_en/main_file.html
/usr/share/tubes2trial/help_en/support.html
/usr/share/tubes2trial/help_en/local_pinout.html
/usr/share/tubes2trial/help_en/registration.html
/usr/share/tubes2trial/help_en/sign_euro.html
/usr/share/tubes2trial/help_en/sign_philips.html
/usr/share/tubes2trial/help_en/local_table.html
/usr/share/tubes2trial/help_en/sign_cv.html
/usr/share/tubes2trial/help_en/sign_soviet.html
/usr/share/tubes2trial/help_en/dialog_sort.html
/usr/share/tubes2trial/help_en/introduction.html
/usr/share/tubes2trial/help_en/pics/dialog_set.jpg
/usr/share/tubes2trial/help_en/pics/local1.jpg
/usr/share/tubes2trial/help_en/pics/dialog_psearch.jpg
/usr/share/tubes2trial/help_en/pics/main3.jpg
/usr/share/tubes2trial/help_en/pics/dialog_tsearchallcat.jpg
/usr/share/tubes2trial/help_en/pics/local4.jpg
/usr/share/tubes2trial/help_en/pics/local2.jpg
/usr/share/tubes2trial/help_en/pics/main2.jpg
/usr/share/tubes2trial/help_en/pics/local3.jpg
/usr/share/tubes2trial/help_en/pics/dialog_sort.jpg
/usr/share/tubes2trial/help_en/pics/main1.jpg
/usr/share/tubes2trial/help_en/pics/main5.jpg
/usr/share/tubes2trial/help_en/pics/main4.jpg
/usr/share/tubes2trial/help_en/pics/dialog_tsearch.jpg
/usr/share/tubes2trial/help_en/dialog_tsearch.html
/usr/share/tubes2trial/help_en/sign_mazda.html
/usr/share/tubes2trial/help_en/dialog_settings.html
/usr/share/tubes2trial/help_en/main_search.html
/usr/share/tubes2trial/help_en/sign_usa.html
/usr/share/tubes2trial/help_en/cmdparams.html
/usr/share/tubes2trial/help_en/sign_brimar.html
/usr/share/tubes2trial/help_en/main_view.html
/usr/share/tubes2trial/help_en/contact.html
/usr/share/tubes2trial/help_en/local_bms.html
/usr/share/tubes2trial/help_en/main_bms.html
/usr/share/tubes2trial/help_en/index.html
/usr/share/tubes2trial/help_en/main_help.html
/usr/share/tubes2trial/help_en/hotkeys.html
/usr/share/tubes2trial/help_en/free_registration.html
/usr/share/tubes2trial/help_en/dialog_psearch.html
/usr/share/tubes2trial/help_en/local_desc.html
