Group: Sciences/Other
License: GPL
Name: tubes2oe
Packager: Pozsar Zsolt <pozsarzs@gmail.com>
Release: 1
Summary: Electrontube catalog
Url: http://www.pozsarzs.hu/tubes/tubes_en.html
Vendor: Pozsar Zsolt
Version: 2.2

%description
This is an electrontube catalogue application.
This is open source version of Tubes2 commercial software.
Different between both software is database update rate only.
Its database contents base type, pin-out and some parameters
of components. Application contains tube characteristic
drawer tool. You can redistribute this version and/or modify
it under the terms of the GNU GPL 3.0 or later.

%files
/usr/share/applications/tubes2oe.desktop
/usr/share/doc/tubes2oe/VERSION
/usr/share/doc/tubes2oe/hu/ordrform.txt
/usr/share/doc/tubes2oe/hu/README
/usr/share/doc/tubes2oe/sample/sample-triode.t2c
/usr/share/doc/tubes2oe/sample/sample-triode-2.csv
/usr/share/doc/tubes2oe/sample/sample-triode-1.csv
/usr/share/doc/tubes2oe/ordrform.txt
/usr/share/doc/tubes2oe/README
/usr/share/doc/tubes2oe/AUTHORS
/usr/share/doc/tubes2oe/COPYING
/usr/share/doc/tubes2oe/ChangeLog
/usr/share/man/man5/cxedf.5
/usr/share/man/man5/t2c.5
/usr/share/man/man5/xedf.5
/usr/share/man/man1/tubes2oe.1
/usr/share/man/hu/man5/cxedf.5
/usr/share/man/hu/man5/t2c.5
/usr/share/man/hu/man5/xedf.5
/usr/share/man/hu/man1/tubes2oe.1
/usr/share/pixmaps/tubes2oe.xpm
/usr/share/tubes2oe/index.csv
/usr/share/tubes2oe/help_en/sign_usa.html
/usr/share/tubes2oe/help_en/order.html
/usr/share/tubes2oe/help_en/sign_cv.html
/usr/share/tubes2oe/help_en/sign_euro.html
/usr/share/tubes2oe/help_en/sign_philips.html
/usr/share/tubes2oe/help_en/sign_mazda.html
/usr/share/tubes2oe/help_en/about.html
/usr/share/tubes2oe/help_en/sign_soviet.html
/usr/share/tubes2oe/help_en/contact.html
/usr/share/tubes2oe/help_en/hotkeys.html
/usr/share/tubes2oe/help_en/sign_brimar.html
/usr/share/tubes2oe/help_en/index.html
/usr/share/tubes2oe/help_en/cmdparams.html
/usr/share/tubes2oe/help_hu/sign_usa.html
/usr/share/tubes2oe/help_hu/order.html
/usr/share/tubes2oe/help_hu/sign_cv.html
/usr/share/tubes2oe/help_hu/sign_euro.html
/usr/share/tubes2oe/help_hu/sign_philips.html
/usr/share/tubes2oe/help_hu/sign_mazda.html
/usr/share/tubes2oe/help_hu/about.html
/usr/share/tubes2oe/help_hu/sign_soviet.html
/usr/share/tubes2oe/help_hu/contact.html
/usr/share/tubes2oe/help_hu/hotkeys.html
/usr/share/tubes2oe/help_hu/sign_brimar.html
/usr/share/tubes2oe/help_hu/index.html
/usr/share/tubes2oe/help_hu/cmdparams.html
/usr/share/tubes2oe/subst.dat
/usr/share/tubes2oe/library_en/20.txt
/usr/share/tubes2oe/library_en/35.txt
/usr/share/tubes2oe/library_en/50.xedf
/usr/share/tubes2oe/library_en/59.xedf
/usr/share/tubes2oe/library_en/18.txt
/usr/share/tubes2oe/library_en/37.txt
/usr/share/tubes2oe/library_en/58.txt
/usr/share/tubes2oe/library_en/03.txt
/usr/share/tubes2oe/library_en/01.txt
/usr/share/tubes2oe/library_en/41.txt
/usr/share/tubes2oe/library_en/33.txt
/usr/share/tubes2oe/library_en/56.xedf
/usr/share/tubes2oe/library_en/43.xedf
/usr/share/tubes2oe/library_en/07.xedf
/usr/share/tubes2oe/library_en/21.txt
/usr/share/tubes2oe/library_en/05.xedf
/usr/share/tubes2oe/library_en/47.xedf
/usr/share/tubes2oe/library_en/03.xedf
/usr/share/tubes2oe/library_en/60.xedf
/usr/share/tubes2oe/library_en/48.xedf
/usr/share/tubes2oe/library_en/61.xedf
/usr/share/tubes2oe/library_en/46.xedf
/usr/share/tubes2oe/library_en/24.xedf
/usr/share/tubes2oe/library_en/57.txt
/usr/share/tubes2oe/library_en/43.txt
/usr/share/tubes2oe/library_en/55.txt
/usr/share/tubes2oe/library_en/51.xedf
/usr/share/tubes2oe/library_en/58.xedf
/usr/share/tubes2oe/library_en/52.xedf
/usr/share/tubes2oe/library_en/38.xedf
/usr/share/tubes2oe/library_en/23.xedf
/usr/share/tubes2oe/library_en/53.xedf
/usr/share/tubes2oe/library_en/15.xedf
/usr/share/tubes2oe/library_en/42.xedf
/usr/share/tubes2oe/library_en/31.xedf
/usr/share/tubes2oe/library_en/30.txt
/usr/share/tubes2oe/library_en/04.txt
/usr/share/tubes2oe/library_en/34.xedf
/usr/share/tubes2oe/library_en/32.xedf
/usr/share/tubes2oe/library_en/20.xedf
/usr/share/tubes2oe/library_en/53.txt
/usr/share/tubes2oe/library_en/19.xedf
/usr/share/tubes2oe/library_en/24.txt
/usr/share/tubes2oe/library_en/46.txt
/usr/share/tubes2oe/library_en/44.txt
/usr/share/tubes2oe/library_en/36.txt
/usr/share/tubes2oe/library_en/33.xedf
/usr/share/tubes2oe/library_en/62.xedf
/usr/share/tubes2oe/library_en/30.xedf
/usr/share/tubes2oe/library_en/54.txt
/usr/share/tubes2oe/library_en/27.txt
/usr/share/tubes2oe/library_en/59.txt
/usr/share/tubes2oe/library_en/02.txt
/usr/share/tubes2oe/library_en/22.xedf
/usr/share/tubes2oe/library_en/60.txt
/usr/share/tubes2oe/library_en/17.xedf
/usr/share/tubes2oe/library_en/62.txt
/usr/share/tubes2oe/library_en/27.xedf
/usr/share/tubes2oe/library_en/01.xedf
/usr/share/tubes2oe/library_en/40.xedf
/usr/share/tubes2oe/library_en/29.txt
/usr/share/tubes2oe/library_en/36.xedf
/usr/share/tubes2oe/library_en/41.xedf
/usr/share/tubes2oe/library_en/02.xedf
/usr/share/tubes2oe/library_en/version.txt
/usr/share/tubes2oe/library_en/32.txt
/usr/share/tubes2oe/library_en/15.txt
/usr/share/tubes2oe/library_en/23.txt
/usr/share/tubes2oe/library_en/45.xedf
/usr/share/tubes2oe/library_en/51.txt
/usr/share/tubes2oe/library_en/49.xedf
/usr/share/tubes2oe/library_en/45.txt
/usr/share/tubes2oe/library_en/28.xedf
/usr/share/tubes2oe/library_en/57.xedf
/usr/share/tubes2oe/library_en/35.xedf
/usr/share/tubes2oe/library_en/31.txt
/usr/share/tubes2oe/library_en/38.txt
/usr/share/tubes2oe/library_en/13.txt
/usr/share/tubes2oe/library_en/54.xedf
/usr/share/tubes2oe/library_en/48.txt
/usr/share/tubes2oe/library_en/63.xedf
/usr/share/tubes2oe/library_en/17.txt
/usr/share/tubes2oe/library_en/news.txt
/usr/share/tubes2oe/library_en/44.xedf
/usr/share/tubes2oe/library_en/07.txt
/usr/share/tubes2oe/library_en/49.txt
/usr/share/tubes2oe/library_en/28.txt
/usr/share/tubes2oe/library_en/22.txt
/usr/share/tubes2oe/library_en/50.txt
/usr/share/tubes2oe/library_en/19.txt
/usr/share/tubes2oe/library_en/39.xedf
/usr/share/tubes2oe/library_en/61.txt
/usr/share/tubes2oe/library_en/63.txt
/usr/share/tubes2oe/library_en/04.xedf
/usr/share/tubes2oe/library_en/26.xedf
/usr/share/tubes2oe/library_en/52.txt
/usr/share/tubes2oe/library_en/06.txt
/usr/share/tubes2oe/library_en/05.txt
/usr/share/tubes2oe/library_en/56.txt
/usr/share/tubes2oe/library_en/34.txt
/usr/share/tubes2oe/library_en/42.txt
/usr/share/tubes2oe/library_en/21.xedf
/usr/share/tubes2oe/library_en/47.txt
/usr/share/tubes2oe/library_en/37.xedf
/usr/share/tubes2oe/library_en/26.txt
/usr/share/tubes2oe/library_en/18.xedf
/usr/share/tubes2oe/library_en/39.txt
/usr/share/tubes2oe/library_en/55.xedf
/usr/share/tubes2oe/library_en/40.txt
/usr/share/tubes2oe/library_en/06.xedf
/usr/share/tubes2oe/library_en/13.xedf
/usr/share/tubes2oe/library_en/29.xedf
/usr/share/tubes2oe/library_hu/20.txt
/usr/share/tubes2oe/library_hu/35.txt
/usr/share/tubes2oe/library_hu/50.xedf
/usr/share/tubes2oe/library_hu/59.xedf
/usr/share/tubes2oe/library_hu/18.txt
/usr/share/tubes2oe/library_hu/37.txt
/usr/share/tubes2oe/library_hu/58.txt
/usr/share/tubes2oe/library_hu/03.txt
/usr/share/tubes2oe/library_hu/01.txt
/usr/share/tubes2oe/library_hu/41.txt
/usr/share/tubes2oe/library_hu/33.txt
/usr/share/tubes2oe/library_hu/56.xedf
/usr/share/tubes2oe/library_hu/43.xedf
/usr/share/tubes2oe/library_hu/07.xedf
/usr/share/tubes2oe/library_hu/21.txt
/usr/share/tubes2oe/library_hu/05.xedf
/usr/share/tubes2oe/library_hu/47.xedf
/usr/share/tubes2oe/library_hu/03.xedf
/usr/share/tubes2oe/library_hu/60.xedf
/usr/share/tubes2oe/library_hu/48.xedf
/usr/share/tubes2oe/library_hu/61.xedf
/usr/share/tubes2oe/library_hu/46.xedf
/usr/share/tubes2oe/library_hu/24.xedf
/usr/share/tubes2oe/library_hu/57.txt
/usr/share/tubes2oe/library_hu/43.txt
/usr/share/tubes2oe/library_hu/55.txt
/usr/share/tubes2oe/library_hu/51.xedf
/usr/share/tubes2oe/library_hu/58.xedf
/usr/share/tubes2oe/library_hu/52.xedf
/usr/share/tubes2oe/library_hu/38.xedf
/usr/share/tubes2oe/library_hu/23.xedf
/usr/share/tubes2oe/library_hu/53.xedf
/usr/share/tubes2oe/library_hu/15.xedf
/usr/share/tubes2oe/library_hu/42.xedf
/usr/share/tubes2oe/library_hu/31.xedf
/usr/share/tubes2oe/library_hu/30.txt
/usr/share/tubes2oe/library_hu/04.txt
/usr/share/tubes2oe/library_hu/34.xedf
/usr/share/tubes2oe/library_hu/32.xedf
/usr/share/tubes2oe/library_hu/20.xedf
/usr/share/tubes2oe/library_hu/53.txt
/usr/share/tubes2oe/library_hu/19.xedf
/usr/share/tubes2oe/library_hu/24.txt
/usr/share/tubes2oe/library_hu/46.txt
/usr/share/tubes2oe/library_hu/44.txt
/usr/share/tubes2oe/library_hu/36.txt
/usr/share/tubes2oe/library_hu/33.xedf
/usr/share/tubes2oe/library_hu/62.xedf
/usr/share/tubes2oe/library_hu/30.xedf
/usr/share/tubes2oe/library_hu/54.txt
/usr/share/tubes2oe/library_hu/27.txt
/usr/share/tubes2oe/library_hu/59.txt
/usr/share/tubes2oe/library_hu/02.txt
/usr/share/tubes2oe/library_hu/22.xedf
/usr/share/tubes2oe/library_hu/60.txt
/usr/share/tubes2oe/library_hu/17.xedf
/usr/share/tubes2oe/library_hu/62.txt
/usr/share/tubes2oe/library_hu/27.xedf
/usr/share/tubes2oe/library_hu/01.xedf
/usr/share/tubes2oe/library_hu/40.xedf
/usr/share/tubes2oe/library_hu/29.txt
/usr/share/tubes2oe/library_hu/36.xedf
/usr/share/tubes2oe/library_hu/41.xedf
/usr/share/tubes2oe/library_hu/02.xedf
/usr/share/tubes2oe/library_hu/version.txt
/usr/share/tubes2oe/library_hu/32.txt
/usr/share/tubes2oe/library_hu/15.txt
/usr/share/tubes2oe/library_hu/23.txt
/usr/share/tubes2oe/library_hu/45.xedf
/usr/share/tubes2oe/library_hu/51.txt
/usr/share/tubes2oe/library_hu/49.xedf
/usr/share/tubes2oe/library_hu/45.txt
/usr/share/tubes2oe/library_hu/28.xedf
/usr/share/tubes2oe/library_hu/57.xedf
/usr/share/tubes2oe/library_hu/35.xedf
/usr/share/tubes2oe/library_hu/31.txt
/usr/share/tubes2oe/library_hu/38.txt
/usr/share/tubes2oe/library_hu/13.txt
/usr/share/tubes2oe/library_hu/54.xedf
/usr/share/tubes2oe/library_hu/48.txt
/usr/share/tubes2oe/library_hu/63.xedf
/usr/share/tubes2oe/library_hu/17.txt
/usr/share/tubes2oe/library_hu/news.txt
/usr/share/tubes2oe/library_hu/44.xedf
/usr/share/tubes2oe/library_hu/07.txt
/usr/share/tubes2oe/library_hu/49.txt
/usr/share/tubes2oe/library_hu/28.txt
/usr/share/tubes2oe/library_hu/22.txt
/usr/share/tubes2oe/library_hu/50.txt
/usr/share/tubes2oe/library_hu/19.txt
/usr/share/tubes2oe/library_hu/39.xedf
/usr/share/tubes2oe/library_hu/61.txt
/usr/share/tubes2oe/library_hu/63.txt
/usr/share/tubes2oe/library_hu/04.xedf
/usr/share/tubes2oe/library_hu/26.xedf
/usr/share/tubes2oe/library_hu/52.txt
/usr/share/tubes2oe/library_hu/06.txt
/usr/share/tubes2oe/library_hu/05.txt
/usr/share/tubes2oe/library_hu/56.txt
/usr/share/tubes2oe/library_hu/34.txt
/usr/share/tubes2oe/library_hu/42.txt
/usr/share/tubes2oe/library_hu/21.xedf
/usr/share/tubes2oe/library_hu/47.txt
/usr/share/tubes2oe/library_hu/37.xedf
/usr/share/tubes2oe/library_hu/26.txt
/usr/share/tubes2oe/library_hu/18.xedf
/usr/share/tubes2oe/library_hu/39.txt
/usr/share/tubes2oe/library_hu/55.xedf
/usr/share/tubes2oe/library_hu/40.txt
/usr/share/tubes2oe/library_hu/06.xedf
/usr/share/tubes2oe/library_hu/13.xedf
/usr/share/tubes2oe/library_hu/29.xedf
/usr/share/tubes2oe/base/xo2.png
/usr/share/tubes2oe/base/b13d.png
/usr/share/tubes2oe/base/b9a.png
/usr/share/tubes2oe/base/x7.png
/usr/share/tubes2oe/base/xo6.png
/usr/share/tubes2oe/base/u5.png
/usr/share/tubes2oe/base/s8.png
/usr/share/tubes2oe/base/x5.png
/usr/share/tubes2oe/base/rts-11.png
/usr/share/tubes2oe/base/crt-14.png
/usr/share/tubes2oe/base/w8.png
/usr/share/tubes2oe/base/eugrd.png
/usr/share/tubes2oe/base/ho1.png
/usr/share/tubes2oe/base/xs9.png
/usr/share/tubes2oe/base/w8a.png
/usr/share/tubes2oe/base/b12a.png
/usr/share/tubes2oe/base/wire-9.png
/usr/share/tubes2oe/base/es1.png
/usr/share/tubes2oe/base/u4.png
/usr/share/tubes2oe/base/t9.png
/usr/share/tubes2oe/base/mo3.png
/usr/share/tubes2oe/base/x6.png
/usr/share/tubes2oe/base/b9aplus.png
/usr/share/tubes2oe/base/sk-118.png
/usr/share/tubes2oe/base/sk-136.png
/usr/share/tubes2oe/base/crt-11a.png
/usr/share/tubes2oe/base/xa3.png
/usr/share/tubes2oe/base/wire-2a.png
/usr/share/tubes2oe/base/eu4.png
/usr/share/tubes2oe/base/sk-185.png
/usr/share/tubes2oe/base/xb4.png
/usr/share/tubes2oe/base/b5.png
/usr/share/tubes2oe/base/k5.png
/usr/share/tubes2oe/base/p5.png
/usr/share/tubes2oe/base/b8g.png
/usr/share/tubes2oe/base/wire-7a.png
/usr/share/tubes2oe/base/bb7.png
/usr/share/tubes2oe/base/sk-197.png
/usr/share/tubes2oe/base/crt-14b.png
/usr/share/tubes2oe/base/wire-4.png
/usr/share/tubes2oe/base/crt-11.png
/usr/share/tubes2oe/base/crt-14a.png
/usr/share/tubes2oe/base/xc4.png
/usr/share/tubes2oe/base/r8.png
/usr/share/tubes2oe/base/y11.png
/usr/share/tubes2oe/base/k5a.png
/usr/share/tubes2oe/base/xa5.png
/usr/share/tubes2oe/base/dip-16.png
/usr/share/tubes2oe/base/eu5.png
/usr/share/tubes2oe/base/b14a.png
/usr/share/tubes2oe/base/f5.png
/usr/share/tubes2oe/base/solder_tag_16.png
/usr/share/tubes2oe/base/b9d.png
/usr/share/tubes2oe/base/xa4.png
/usr/share/tubes2oe/base/b7g.png
/usr/share/tubes2oe/base/x8.png
/usr/share/tubes2oe/base/p7.png
/usr/share/tubes2oe/base/y9.png
/usr/share/tubes2oe/base/k8.png
/usr/share/tubes2oe/base/uo1.png
/usr/share/tubes2oe/base/b8d.png
/usr/share/tubes2oe/base/eu3.png
/usr/share/tubes2oe/base/s5.png
/usr/share/tubes2oe/base/ed3.png
/usr/share/tubes2oe/base/u6.png
/usr/share/tubes2oe/base/sk-116.png
/usr/share/tubes2oe/base/ed2.png
/usr/share/tubes2oe/base/wire-6a.png
/usr/share/tubes2oe/base/xs10.png
/usr/share/tubes2oe/base/wire-2.png
/usr/share/tubes2oe/base/xs7.png
/usr/share/tubes2oe/base/xa11.png
/usr/share/tubes2oe/base/xa10.png
/usr/share/tubes2oe/base/wire-5.png
/usr/share/tubes2oe/base/to-100.png
/usr/share/tubes2oe/base/x8a.png
/usr/share/tubes2oe/base/k8a.png
/usr/share/tubes2oe/base/a10.png
/usr/share/tubes2oe/base/wire-3.png
/usr/share/tubes2oe/base/xo11.png
/usr/share/tubes2oe/base/es2.png
/usr/share/tubes2oe/base/spec1.png
/usr/share/tubes2oe/base/crt-18.png
/usr/share/tubes2oe/base/y3.png
/usr/share/tubes2oe/base/crt-14c.png
/usr/share/tubes2oe/base/y5.png
/usr/share/tubes2oe/base/sk-207.png
/usr/share/tubes2oe/base/a8.png
/usr/share/tubes2oe/base/sk-176.png
/usr/share/tubes2oe/base/xe7.png
/usr/share/tubes2oe/base/sk-182.png
/usr/share/tubes2oe/base/ed1.png
/usr/share/tubes2oe/base/b13b.png
/usr/share/tubes2oe/base/unknown.png
/usr/share/tubes2oe/base/wire-4a.png
/usr/share/tubes2oe/base/wire-5a.png
/usr/share/tubes2oe/base/crt-12.png
/usr/share/tubes2oe/base/b12e.png
/usr/share/tubes2oe/base/k8alh.png
/usr/share/tubes2oe/base/b6.png
/usr/share/tubes2oe/base/b17a.png
/usr/share/tubes2oe/base/y6.png
/usr/share/tubes2oe/base/b7.png
/usr/share/tubes2oe/base/x3.png
/usr/share/tubes2oe/base/eo1.png
/usr/share/tubes2oe/base/u7.png
/usr/share/tubes2oe/base/wire-3a.png
/usr/share/locale/hu/LC_MESSAGES/tubes2oe.mo
/usr/bin/tubes2oe
