.TH "t2c" "5" "" "Pozsar Zsolt" "Project file for Tubes2"
.SH "NAME"
.LP 
*.t2c - Project file for Tubes2
.SH "DESCRIPTION"
.LP 
This type of file used by Characteristic drawer tool of
Tubes2 electron tube catalog application. You can use it for
Tubes2 v2.2 or later.
.LP
.SH "AUTHOR"
.LP 
Pozsar Zsolt
.br
Web:    http://www.pozsarzs.hu/en/
.br
E-mail: info@pozsarzs.hu
