.TH "t2c" "5" "" "Pozsár Zsolt" "Projekt fájl a Tubes2-höz"
.SH "NAME"
.LP 
*.t2c - Projekt file a Tubes2-höz
.SH "DESCRIPTION"
.LP 
Ezt a fájltípust a Tubes2 elektroncső katalógus alkalmazás
jelleggörbe rajzoló segédeszköze használja a projektek
tárolására. Használható a Tubes2 v2.2 vagy későbbi változatával.
.LP
.SH "AUTHOR"
.LP 
Pozsar Zsolt
.br
Web:    http://www.pozsarzs.hu
.br
E-mail: pozsarzs@gmail.com
