.TH "tubes2oe" "1" "2.2" "Pozsar Zsolt" "Electron tube catalog"
.SH "NAME"
.LP 
Tubes2 \- Electron tube catalog
.SH "SYNTAX"
.LP
tubes2oe [-d | --dontcheckupdate | -h | --help | -o | --offline | -v | --version]
.br 
.SH OPTIONS
.TP
.B \-d \-\-dontcheckupdate
Do not check application and database update on internet
.TP
.B \-h \-\-help
Write useable parameters to console.
.TP
.B \-o \-\-offline
Switch to off-line operation mode.
.TP
.B \-v \-\-version
Write version and build information to console.
.SH "DESCRIPTION"
.LP 
This is open source version of Tubes2 commercial software. Different between both
software is database update rate only. Its database contents base pin-out
and some parameters of components. Database contains record of more than four
thousand electron tubes. There are CV/M2/VT type substitution searcher and tube
characteristic drawer tool (except CUI version). You can redistribute this version
and/or modify it under the terms of the GNU GPL 3.0 or later.
.LP
For more information see documentation in directory of application.
.br
.SH "ENVIRONMENTAL VARIABLE"
.LP 
\fBLANG\fP
.br
You can set language of labels with these variables.
If it is a non-supported language, text will be English.
Format: en, en_US.
.br
Available language are English and Hungarian, now.
.SH "AUTHOR"
.LP 
Pozsar Zsolt
.br
Web:    http://www.pozsarzs.hu/en/
.br
E-mail: info@pozsarzs.hu
