.TH "tubes2oe" "1" "2.2" "Pozsár Zsolt" "Elektroncső katalógus"
.SH "NÉV"
.LP 
Tubes \- Elektroncső katalógus
.SH "ÁTTEKINTÉS"
.LP
tubes2oe [-d | --dontcheckupdate | -h | --help | -o | --offline | -v | --version]
.br 
.SH OPCIÓK
.TP
.B \-d \-\-dontcheckupdate
Nem ellenőrzi az interneten elérhető frissítéseket.
.TP
.B \-h \-\-help
Kiírja a használható paramétereket a konzolra.
.TP
.B \-o \-\-offline
Off-line működési módba kapcsol.
.TP
.B \-v \-\-version
Kiírja a verzió és a fordítási információkat a konzolra.
.SH "LEÍRÁS"
Ez a Tubes2 kereskedelmi szoftver nyílt forrású változata. A különbség a
két változat között csak az adatbázis frissítés gyakorisága. Az alkalmazás
adatbázisa több mint 4000 elektroncső csőfejbekötését és
fontosabb adatait tartalmazza. Az alkalmazás tartalmaz egy CV/M2/VT típus
helyettesítés keresőt és a grafikus változat egy karakterisztika rajzoló
segédeszközt is.
.LP
Bővebb információt az alkalmazás könyvtárában található documentációban talál.
.LP 
.SH "KÖRNYEZETI VÁLTOZÓK"
.LP 
\fBLANG\fP
.br
Ezzel a környezeti változóval állíthatjuk be a program nyelvezetét. Ha
ez egy nem támogatott nyelv, akkor a feliratok angol nyelvűek lesznek.
Alak: hu, hu_HU.
.br
Jelenleg elérhető nyelvek: angol, magyar.
.SH "SZERZŐ"
.LP 
Pozsár Zsolt
.br
Web:    http://www.pozsarzs.hu
.br
E-mail: info@pozsarzs.hu
