.TH "tubes2trial" "7" "2.1" "Pozsár Zsolt" "Elektroncső katalógus"
.SH "NÉV"
.LP 
Tubes \- Elektroncső katalógus
.SH "ÁTTEKINTÉS"
.LP
tubes2trial [-h | --help | -o | -offline | -v | --version]
.br
.SH OPCIÓK
.TP
.B \-h \-\-help
Kiírja a használható paramétereket a konzolra.
.TP
.B \-o \-\-offline
Off-line működési módba kapcsol.
.TP
.B \-v \-\-version
Kiírja a verziószámot a konzolra.
.SH "LEÍRÁS"
Ez egy folyamatosan bővülő elektroncső katalógus. Az alkalmazás adatbázisa
tartalmazza az elektroncsövek csőfej típusát, csőfejbekötését és fontosabb
adatait. A honlapról a Tubes kétféle változatát töltheti le:
.LP
1. A "trial" változat segítségével a teljes értékű termék megvétele előtt
díjmentesen kipróbálhatja és eldöntheti, hogy megfelel-e az elvárásának.
A "trial" változat a GNU GPL 3.0 szerint módosítható és/vagy terjeszthető.
.LP
2. A "pro" változat megvásárlásával a felhasználó át nem ruházható jogot szerez
az alkalmazásnak és a frissítéseinek korlátozás nélküli használatára.
A "pro" változat GARANCIA NÉLKÜL kerül terjesztésre. Az alkalmazás a személyre
szóló regisztrációs kulcs nélkül szabadon másolható és terjeszthető, de a
visszafejtése, a belső felépítésének elemzése tilos. A Tubes2 a
regisztráláskor megadott megadott számú számítógépen lévő összes operációs
rendszerre telepíthető, és azokat a számítógép összes felhasználója
használhatja.
.LP
Bővebb információt az alkalmazás könyvtárában található documentációban talál.
.LP 
.SH "KÖRNYEZETI VÁLTOZÓK"
.LP 
\fBLANG\fP
.br
Ezzel a környezeti változóval állíthatjuk be a program nyelvezetét. Ha
ez egy nem támogatott nyelv, akkor a feliratok angol nyelvűek lesznek.
Alak: hu, hu_HU.
.br
Jelenleg elérhető nyelvek: angol, magyar.
.SH "SZERZŐ"
.LP 
Pozsár Zsolt
.br
Web:    http://www.pozsarzs.hu
.br
E-mail: pozsarzs@gmail.com
